import { renderToStaticMarkup } from "react-dom/server";
import RootLayout, { metadata } from "./layout";

jest.mock("next/font/google", () => ({
  Geist: () => ({ variable: "geist-sans" }),
  Geist_Mono: () => ({ variable: "geist-mono" }),
}));

describe("Root layout", () => {
  it("exposes metadata defaults", () => {
    expect(metadata.title).toBe("Create Next App");
    expect(metadata.description).toBe("Generated by create next app");
  });

  it("wraps children with base layout markup", () => {
    const markup = renderToStaticMarkup(
      <RootLayout>
        <div>Child content</div>
      </RootLayout>,
    );
    const doc = new DOMParser().parseFromString(markup, "text/html");

    expect(doc.body.textContent).toContain("Child content");
    expect(doc.documentElement.getAttribute("lang")).toBe("en");
    expect(doc.body.className).toContain("geist-sans");
    expect(doc.body.className).toContain("geist-mono");
    expect(doc.body.className).toContain("antialiased");
  });
});
